import{a as q,i as m,S as x}from"./assets/vendor-DFCQGEf1.js";(function(){const t=document.createElement("link").relList;if(t&&t.supports&&t.supports("modulepreload"))return;for(const s of document.querySelectorAll('link[rel="modulepreload"]'))i(s);new MutationObserver(s=>{for(const o of s)if(o.type==="childList")for(const u of o.addedNodes)u.tagName==="LINK"&&u.rel==="modulepreload"&&i(u)}).observe(document,{childList:!0,subtree:!0});function r(s){const o={};return s.integrity&&(o.integrity=s.integrity),s.referrerPolicy&&(o.referrerPolicy=s.referrerPolicy),s.crossOrigin==="use-credentials"?o.credentials="include":s.crossOrigin==="anonymous"?o.credentials="omit":o.credentials="same-origin",o}function i(s){if(s.ep)return;s.ep=!0;const o=r(s);fetch(s.href,o)}})();const A="50174992-a37a037319a3aab3105cbedec",I="https://pixabay.com/api/",_=15;async function w(e,t){const r={key:A,q:e,image_type:"photo",orientation:"horizontal",safesearch:!0,page:t,per_page:_};try{return(await q.get(I,{params:r})).data}catch(i){throw m.error({title:"Warning!",message:"Failed to load images. Try again later.",position:"topRight",timeout:5e3}),i}}const n=document.querySelector("#load-more"),l=document.querySelector("#gallery"),c=document.querySelector("#loader"),d=document.querySelector("#bottom-loader-text");let a;function $(e){const t=e.map(({webformatURL:r,largeImageURL:i,tags:s,likes:o,views:u,comments:R,downloads:S})=>`
      <li class="gallery-item">
        <a href="${i}">
          <img src="${r}" alt="${s}" loading="lazy"/>
        </a>
        <div class="info">
          <div class="info-item"><p class="label">Likes</p><p class="value">${o}</p></div>
          <div class="info-item"><p class="label">Views</p><p class="value">${u}</p></div>
          <div class="info-item"><p class="label">Comments</p><p class="value">${R}</p></div>
          <div class="info-item"><p class="label">Downloads</p><p class="value">${S}</p></div>
        </div>
      </li>
    `).join("");l&&(l.insertAdjacentHTML("beforeend",t),a?a.refresh():(a=new x(".gallery a",{captionsData:"alt",captionDelay:250,closeText:"✖",close:!0,showCounter:!1}),a.on("show.simplelightbox",y),a.on("next.simplelightbox",y),a.on("prev.simplelightbox",y)))}function y(){const e=document.querySelector(".sl-image");e&&e.classList.remove("sl-image")}function G(){var t;const e=(t=l==null?void 0:l.firstElementChild)==null?void 0:t.getBoundingClientRect().height;e&&window.scrollBy({top:e*2,behavior:"smooth"})}function B(){l.innerHTML=""}function b(){c==null||c.classList.remove("hidden")}function g(){c==null||c.classList.add("hidden")}function M(){n==null||n.classList.remove("hidden")}function v(){n==null||n.classList.add("hidden")}function O(){d==null||d.classList.remove("hidden")}function f(){d==null||d.classList.add("hidden")}const L=document.querySelector("#search-form"),C=document.querySelector("#load-more");let p=1,h="",P=0;const F=15;L.addEventListener("submit",async e=>{if(e.preventDefault(),h=e.target.elements["search-text"].value.trim(),p=1,!!h){B(),b(),v(),f();try{const t=await w(h,p);P=Math.ceil(t.totalHits/F),E(t)&&L.reset()}catch{m.error({title:"Error",message:"Failed to fetch images. Please try again later.",position:"topRight"}),g(),f()}}});C.addEventListener("click",async()=>{p+=1,b(),O(),v();try{const e=await w(h,p);E(e)&&G()}catch{m.error({title:"Error",message:"Failed to load more images.",position:"topRight"}),g(),f()}});async function E(e){return e.hits.length?($(e.hits),g(),await T(),f(),p>=P?(v(),m.info({title:"End of Results",message:"We're sorry, but you've reached the end of search results.",position:"topRight"})):M(),!0):(m.info({title:"Info",message:"No images found.",position:"topRight"}),g(),f(),!1)}function T(){const e=document.querySelectorAll("#gallery img"),t=Array.from(e).map(r=>r.complete?Promise.resolve():new Promise(i=>r.onload=i));return Promise.all(t)}
//# sourceMappingURL=index.js.map
