import{a as x,i as f,S as q}from"./assets/vendor-DFCQGEf1.js";(function(){const s=document.createElement("link").relList;if(s&&s.supports&&s.supports("modulepreload"))return;for(const t of document.querySelectorAll('link[rel="modulepreload"]'))i(t);new MutationObserver(t=>{for(const o of t)if(o.type==="childList")for(const u of o.addedNodes)u.tagName==="LINK"&&u.rel==="modulepreload"&&i(u)}).observe(document,{childList:!0,subtree:!0});function r(t){const o={};return t.integrity&&(o.integrity=t.integrity),t.referrerPolicy&&(o.referrerPolicy=t.referrerPolicy),t.crossOrigin==="use-credentials"?o.credentials="include":t.crossOrigin==="anonymous"?o.credentials="omit":o.credentials="same-origin",o}function i(t){if(t.ep)return;t.ep=!0;const o=r(t);fetch(t.href,o)}})();const A="50174992-a37a037319a3aab3105cbedec",I="https://pixabay.com/api/",_=15;async function b(e,s){const r={key:A,q:e,image_type:"photo",orientation:"horizontal",safesearch:!0,page:s,per_page:_};try{return(await x.get(I,{params:r})).data}catch(i){throw f.error({title:"Warning!",message:"Failed to load images. Try again later.",position:"topRight",timeout:5e3}),i}}const n=document.querySelector("#load-more"),l=document.querySelector("#gallery"),c=document.querySelector("#loader"),d=document.querySelector("#bottom-loader-text");let a;function $(e){const s=e.map(({webformatURL:r,largeImageURL:i,tags:t,likes:o,views:u,comments:S,downloads:P})=>`
      <li class="gallery-item">
        <a href="${i}">
          <img src="${r}" alt="${t}" loading="lazy"/>
        </a>
        <div class="info">
          <div class="info-item"><p class="label">Likes</p><p class="value">${o}</p></div>
          <div class="info-item"><p class="label">Views</p><p class="value">${u}</p></div>
          <div class="info-item"><p class="label">Comments</p><p class="value">${S}</p></div>
          <div class="info-item"><p class="label">Downloads</p><p class="value">${P}</p></div>
        </div>
      </li>
    `).join("");l&&(l.insertAdjacentHTML("beforeend",s),a?a.refresh():(a=new q(".gallery a",{captionsData:"alt",captionDelay:250,closeText:"✖",close:!0,showCounter:!1}),a.on("show.simplelightbox",y),a.on("next.simplelightbox",y),a.on("prev.simplelightbox",y)))}function y(){const e=document.querySelector(".sl-image");e&&e.classList.remove("sl-image")}function G(){var s;const e=(s=l==null?void 0:l.firstElementChild)==null?void 0:s.getBoundingClientRect().height;e&&window.scrollBy({top:e*2,behavior:"smooth"})}function B(){l.innerHTML=""}function w(){c==null||c.classList.remove("hidden")}function g(){c==null||c.classList.add("hidden")}function M(){n==null||n.classList.remove("hidden")}function v(){n==null||n.classList.add("hidden")}function O(){d==null||d.classList.remove("hidden")}function m(){d==null||d.classList.add("hidden")}const L=document.querySelector("#search-form"),C=document.querySelector("#load-more");let p=1,h="",E=0;const D=15;L.addEventListener("submit",async e=>{if(e.preventDefault(),h=e.target.elements["search-text"].value.trim(),p=1,!!h){B(),w(),v(),m();try{const s=await b(h,p);E=Math.ceil(s.totalHits/D),R(s)&&L.reset()}catch{f.error({title:"Error",message:"Failed to fetch images. Please try again later.",position:"topRight"}),g(),m()}}});C.addEventListener("click",async()=>{p+=1,w(),O(),v();try{const e=await b(h,p);R(e)&&G()}catch{f.error({title:"Error",message:"Failed to load more images.",position:"topRight"}),g(),m()}});function R(e){return e.hits.length?($(e.hits),g(),m(),p>=E?(v(),f.info({title:"End of Results",message:"We're sorry, but you've reached the end of search results.",position:"topRight"})):M(),!0):(f.info({title:"Info",message:"No images found.",position:"topRight"}),g(),m(),!1)}
//# sourceMappingURL=index.js.map
